### PR TITLE
refactor: tarot card hover effect

### PR DESCRIPTION
**Pull request by michellemeinert**

### CODE REVIEW

**Comment by tofran** [comment]
> @tofran why was this not deployed?

Humm idk, maybe try to update the branch first (from main). As GH is not able to due to merge conflicts.
In this tree (d11d8dc23a510fc1cf9fd54bf51dcb3b9c5515c3) the actions are quite old: https://github.com/significa/significa.co/tree/style/hover-tarot/.github/workflows

**Review by filipeff95 — COMMENTED** [review]
Looks great, but have you tried to make the mouse out transition smoother? Looks a bit harsh when moving the mouse away

https://github.com/significa/significa.co/assets/98809371/a2c19292-6e39-4f90-ad4c-79bdadb87ca1

**Comment by pdrbrnd** [comment]
I like this but I agree with @filipeff95 

not merging until we get that fixed. maybe a simple transition will suffice

**Comment by tofran** [comment]
@filipeff95 @pdrbrnd 
Can we merge this?

cc @michellemeinert

**Comment by pdrbrnd** [comment]
@michellemeinert definitely! looks amazing, thanks

**Pull request merged**
