### PR TITLE
fix: remove forced dark theme

### PR DESCRIPTION
**Pull request by michellemeinert**
https://linear.app/significa/issue/SIGN-581/[bug]-image-comparison-block

additional fix: 
before: 
https://github.com/significa/significa.co/assets/48441148/b268eedc-648a-4ae6-9b47-7ebc03e99d20

after:
https://github.com/significa/significa.co/assets/48441148/8faa986a-9525-4551-9847-bb302a53bf20

### CODE REVIEW

**Review by pdrbrnd — CHANGES_REQUESTED** [review]
why are we adding the mouse listeners to a div instead of the window?
this probably won't work if drag the handle and release it outside of the element

**Comment by michellemeinert** [comment]
> why are we adding the mouse listeners to a div instead of the window? this probably won't work if drag the handle and release it outside of the element

It's because if it's on window all of the comparison components on the page move at the same time! Tomás recorded it in the first screen recording above and the second one is after I move the handlers to the div. 
I just checked regarding moving it outside of the screen, and it's not possible to move it outside but it does create weird behavior where you can move the slider without having the mouse clicked :// I will look into a different fix for it tomorrow

**Comment by pdrbrnd** [comment]
I need to test this locally, will do it today

**Comment by nunopolonia** [comment]
Closing this PR in favor of https://github.com/significa/significa.co/pull/329

**Pull request closed without merging**
