### PR TITLE
feat(about page): change team list and order team name by alphabet

### PR DESCRIPTION
**Pull request by Cleysonlb**
### Changes

- Add Cleyson to team list
- Remove Danilo to team list
- Order team member by alphabet

### Order solution

Using `localeCompare`, this feature has a good compatibility, see on [can i use](https://caniuse.com/?search=localeCompare)

### Result

image

### CODE REVIEW

**Review by pbrandone — APPROVED** [review]
LGTM 🚀

**Review by danilowoz — APPROVED** [review]

**Comment by danilowoz** [comment]
@Cleysonlb please add Rui Ferreira as well

**Review by pedrobslisboa — DISMISSED** [review]
> Remove Danilo to team list

:(

**Comment by Cleysonlb** [comment]
@danilowoz can I merge?

**Comment by pedrobslisboa** [comment]
@Cleysonlb Before merge add Rui Ferreira

**Review by pbrandone — APPROVED** [review]

**Pull request merged**
