### PR TITLE
fix(logo): transition

### PR DESCRIPTION
**Pull request by danilowoz**

### CODE REVIEW

**Comment by pbrandone** [comment]
Deploy preview ready! https://pr-85.significa.io/

**Comment by danilowoz** [comment]
Four minutes build time and with a personal comment from the boss, not bad.

image

**Comment by pbrandone** [comment]
Deploy preview ready! https://pr-85.significa.io/

**Comment by pbrandone** [comment]
Deploy preview ready! https://pr-85.significa.io/

**Pull request merged**
